/**
Zeta core interpreter implementation

The core interpreter expects rigid AST node object layouts generated by
the core parser. This interpreter only serves to allow the Zeta JIT compiler
to compile itself, it should never need to be run after that point, hence
I have cut some corners in terms of its implementation. The language
semantics supported are limited.
*/

#ifndef __INTERP_H__
#define __INTERP_H__

#include "vm.h"

value_t eval_expr(heapptr_t expr);

value_t eval_str(char* cstr);

void test_interp();

#endif

